export const SHOW = 'show'
export const HIDE = 'hide'
export const WIDTHOPEN = 'widthOpen'
export const WIDTHCLOSE = 'widthClose'
export const CURRENTLINK = 'currentLink'
export const SHOWLOADER = 'showLoader'
// export const CONTROLTOKEN = 'controlToken'

// export const ALLROLE = 'allRole'
// export const ACCESSRIGHTS = 'accessRights'
